/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.3.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    jacoco
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)
    implementation(libs.gson)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

application {
    // Define the main class for the application.
    mainClass = "com.ruleengine.App"
}

tasks.named<Test>("test") {
    useJUnitPlatform {
        excludeTags("integration")
    }
    finalizedBy(tasks.jacocoTestReport)
}

tasks.register<Test>("integrationTest") {
    useJUnitPlatform {
        includeTags("integration")
    }
    description = "Runs integration tests"
    group = "verification"
    testClassesDirs = sourceSets["test"].output.classesDirs
    classpath = sourceSets["test"].runtimeClasspath
}

tasks.jacocoTestReport {
    dependsOn(tasks.test)
    reports {
        xml.required = true
        html.required = true
    }
}

tasks.jacocoTestCoverageVerification {
    violationRules {
        rule {
            limit {
                minimum = "0.80".toBigDecimal()
            }
        }
    }
}

tasks.named<Javadoc>("javadoc") {
    options {
        this as StandardJavadocDocletOptions
        addStringOption("Xdoclint:none", "-quiet")
        encoding = "UTF-8"
    }
}

tasks.named("build") {
    dependsOn("javadoc")
    dependsOn(tasks.jacocoTestCoverageVerification)
}

// Parallel GC: ~14% higher throughput than G1GC for this batch workload at 512m.
// GC pause is negligible (<0.1%) with either collector at this allocation rate (~80 B/URL).
tasks.register<JavaExec>("benchmark") {
    description = "Run the rule engine throughput benchmark"
    group = "verification"
    classpath = sourceSets["test"].runtimeClasspath
    mainClass = "com.ruleengine.benchmark.BenchmarkRunner"
    val threadCount = providers.gradleProperty("threads").orElse("1")
    jvmArgs("-XX:+UseParallelGC", "-Xms512m", "-Xmx512m")
    args("42", threadCount.get())
    if (project.hasProperty("profile")) {
        jvmArgs("-XX:StartFlightRecording=filename=${project.layout.buildDirectory.get()}/benchmark.jfr,settings=profile")
    }
    workingDir = project.projectDir
}

tasks.register<JavaExec>("largeBenchmark") {
    description = "Run benchmark with ~100K rules for stress testing"
    group = "verification"
    classpath = sourceSets["test"].runtimeClasspath
    mainClass = "com.ruleengine.benchmark.BenchmarkRunner"
    val threadCount = providers.gradleProperty("threads").orElse("1")
    jvmArgs("-XX:+UseParallelGC", "-Xms4g", "-Xmx4g")
    args("42", threadCount.get(), "large")
    workingDir = project.projectDir
}

tasks.register<JavaExec>("gcBenchmark") {
    description = "Run the benchmark with verbose GC logging for allocation analysis"
    group = "verification"
    classpath = sourceSets["test"].runtimeClasspath
    mainClass = "com.ruleengine.benchmark.BenchmarkRunner"
    val outputDir = layout.buildDirectory.dir("benchmark")
    jvmArgs(
        "-XX:+UseG1GC", "-Xms512m", "-Xmx512m",
        "-Xlog:gc*:file=${outputDir.get()}/gc.log:time,level,tags",
    )
    workingDir = project.projectDir
    dependsOn("testClasses")
    doFirst { outputDir.get().asFile.mkdirs() }
}

tasks.register<JavaExec>("profileBenchmark") {
    description = "Run the benchmark with async-profiler (collapsed stacks + flame graph)"
    group = "verification"
    classpath = sourceSets["test"].runtimeClasspath
    mainClass = "com.ruleengine.benchmark.BenchmarkRunner"
    val apLib = providers.gradleProperty("asyncProfilerLib")
    val outputDir = layout.buildDirectory.dir("benchmark")
    val event = providers.gradleProperty("profileEvent").orElse("cpu")
    jvmArgs(
        "-XX:+UseG1GC", "-Xms512m", "-Xmx512m",
        "-agentpath:${apLib.get()}=start,event=${event.get()},file=${outputDir.get()}/profile.collapsed,collapsed",
    )
    workingDir = project.projectDir
    dependsOn("testClasses")
    doFirst { outputDir.get().asFile.mkdirs() }
}
